# Generated by Django 3.1.3 on 2020-12-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_auto_20201222_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_section',
        ),
        migrations.AddField(
            model_name='student',
            name='institute',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
