# Generated by Django 3.1.3 on 2020-12-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0007_publishedquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedquiz',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
