# Generated by Django 3.1.3 on 2020-12-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_auto_20201223_0230'),
        ('App_Quiz', '0009_auto_20201224_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedquiz',
            name='quiz_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='publishedquiz',
            name='total_attendees',
            field=models.ManyToManyField(null=True, to='App_Login.Student'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='participiants',
            field=models.ManyToManyField(null=True, to='App_Login.Student'),
        ),
    ]
