# Generated by Django 3.1.3 on 2020-12-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_auto_20201223_0230'),
        ('App_Quiz', '0010_auto_20201224_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedquiz',
            name='total_attendees',
            field=models.ManyToManyField(blank=True, to='App_Login.Student'),
        ),
    ]
