# Generated by Django 3.1.3 on 2020-12-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0013_auto_20201224_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
