# Generated by Django 3.1.3 on 2020-12-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0016_auto_20201224_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
    ]
