# Generated by Django 3.1.3 on 2020-12-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0003_auto_20201223_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Write Article Contents Here..'),
        ),
    ]
