# Generated by Django 3.1.3 on 2020-12-22 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Login', '0004_auto_20201223_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=264)),
                ('option1', models.CharField(max_length=264)),
                ('option2', models.CharField(max_length=264)),
                ('option3', models.CharField(max_length=264)),
                ('option4', models.CharField(max_length=264)),
                ('correct_ans', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_creator', to='App_Login.teacher')),
                ('participiants', models.ManyToManyField(to='App_Login.Student')),
                ('quiz', models.ManyToManyField(to='App_Quiz.Question')),
            ],
        ),
    ]
