# Generated by Django 3.1.3 on 2020-12-22 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_auto_20201223_0230'),
        ('App_Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_creator', to='App_Login.teacher'),
        ),
    ]
