# Generated by Django 3.1.3 on 2020-12-23 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0002_auto_20201223_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
