# Generated by Django 3.1.3 on 2020-12-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0003_auto_20201223_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='added',
            new_name='added_to_quiz',
        ),
    ]
