# Generated by Django 3.1.3 on 2020-12-24 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_auto_20201223_0230'),
        ('App_Quiz', '0006_auto_20201223_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_marks', models.IntegerField()),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_published', to='App_Quiz.quiz')),
                ('total_attendees', models.ManyToManyField(to='App_Login.Student')),
            ],
        ),
    ]
