# Generated by Django 3.1.3 on 2020-12-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0008_publishedquiz_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishedquiz',
            options={'verbose_name_plural': 'Published_Quizes'},
        ),
        migrations.AlterModelTable(
            name='publishedquiz',
            table='Published_Quizes',
        ),
    ]
