# Generated by Django 3.1.3 on 2020-12-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0012_auto_20201224_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_published', to='App_Quiz.quiz'),
        ),
    ]
