# Generated by Django 3.1.3 on 2020-12-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0014_quiz_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedquiz',
            name='quiz_marks',
            field=models.IntegerField(blank=True, default=20),
            preserve_default=False,
        ),
    ]
