# Generated by Django 3.1.3 on 2020-12-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0015_auto_20201224_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedquiz',
            name='quiz_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
