# Generated by Django 3.1.3 on 2020-12-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_auto_20201222_1549'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='Teacher',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
